### ISSUE TITLE
Feature request: Continuation downloading

### ISSUE THREAD

**Issue by ce70cdd** [cristian-gabbanini/fem-downloader#8]
When working with an unstable connection and a technique as fragile as scraping, running into dropped connections or errors is quite common.

A common strategy to download a large set of data is continuation. This could be implemented as simple as checking whether a `.webm` and `.web_vtt` file already exists for the correct chapter, and then skipping downloading that chapter and moving on to the next one. Thereby assuming it was correctly downloaded in the past.

As a side effect, this strategy would lessen the load on the server, and possibly side-step account bans.

**Comment by cristian-gabbanini** [comment]
Hi,
Thanks for your suggestion!
Even if on the one hand I do not totally agree with you on the concerns you pose about scraping over an unstable connection, on the other hand I think that would be nice to allow users to resume an incomplete download.
I am not only referring to any download that could have failed due to a unreliable network connection.
I am thinking as well about the downloads which could have been interrupted voluntarily by the user for whatever reason.

Anyway I am not sure if would be enough checking the existence of both the video and/or the subtitle file (which by the way could not be present because subtitle download is optional) because, for example, the download could have stopped halfway down the course.

First things that comes to mind is adding a per course file descriptor which would serve as a pointer to the last successfully downloaded lesson of the each course.
Suggestions are welcome!

Anyway, I am now on vacation in Sicily so I would be able to address this feature request only at the end of the month.
So you have plenty of time to write down every thing that could pertain this issue
Bye!

**Comment by ce70cdd** [comment]
Thanks for your response! Enjoy your vacation, no rush :)

In the meantime I've hotpatched my installed version to replace [lines 230-232 in fem.js](https://github.com/cristian-gabbanini/fem-downloader/blob/master/fem.js#L230-L232) with this:

```js
const filename = `./${courseSlug}/${lessonGroup}/${index}-${lessonTitle}.webm`;

let exists = false;
try { exists = fs.statSync(filename).isFile(); } catch (err) {}
if (exists) {
  console.log(
    `\n${new Date().toLocaleTimeString()}: Skipping: ${index}-${lessonTitle}`
  );
  return Promise.resolve(true);
}

const file = fs.createWriteStream(filename);
```

If I get an error halfway the process, I can just run the same command again, and it would skip all the files that are there. The obvious disadvantage is that if a file is downloaded incorrectly, I have to delete that file manually to trigger it to download again.

The code I've pasted here is my temporary hack, it might be an inspiration, but I would not advise using this exact implementation. What you propose with a file descriptor seems a much better option, although it would also take more implementation time and complexity.

**Comment by ce70cdd** [comment]
> Even if on the one hand I do not totally agree with you on the concerns you pose about scraping

My reservations are about scraping in general, not about scraping over an unstable connection. I meant that scraping is a brittle technique because on most html/css changes on the target website, the scraping script will break. It's tight coupled against implementation details which are likely to change. Scraping will not give you a dropped connection, scraping will give you errors.

But enough about scraping, I'm afraid we have no choice in the matter anyway. It is what is is, considering the nature of this task :)

I've got an example error here:
```
13:37:42: Downloading: <redacted>.webm
 ████████████████████████████████████████ 100% | ETA: 0s | 133337/133337
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo EAI_AGAIN static.frontendmasters.com static.frontendmasters.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
Emitted 'error' event at:
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

This error is actually of downloading the next `web_vtt` file, which is left on the disk with 0 bytes content. The `webm` file matching the progress bar was succesfully downloaded.

**Comment by azy2k9** [comment]
> Thanks for your response! Enjoy your vacation, no rush :)
> 
> In the meantime I've hotpatched my installed version to replace [lines 230-232 in fem.js](https://github.com/cristian-gabbanini/fem-downloader/blob/master/fem.js#L230-L232) with this:
> 
> ```js
> const filename = `./${courseSlug}/${lessonGroup}/${index}-${lessonTitle}.webm`;
> 
> let exists = false;
> try { exists = fs.statSync(filename).isFile(); } catch (err) {}
> if (exists) {
>   console.log(
>     `\n${new Date().toLocaleTimeString()}: Skipping: ${index}-${lessonTitle}`
>   );
>   return Promise.resolve(true);
> }
> 
> const file = fs.createWriteStream(filename);
> ```
> 
> If I get an error halfway the process, I can just run the same command again, and it would skip all the files that are there. The obvious disadvantage is that if a file is downloaded incorrectly, I have to delete that file manually to trigger it to download again.
> 
> The code I've pasted here is my temporary hack, it might be an inspiration, but I would not advise using this exact implementation. What you propose with a file descriptor seems a much better option, although it would also take more implementation time and complexity.

Hello,

Apologies if anything i mention is not possible or not feasible, i'm a junior dev so i'm still learning!

However i was thinking, maybe you could could check the size of the last downloaded file and compare it with the chapter that is going to be downloaded, if they are equal sizes then you know that chapter downloaded successfully, if not then re-download that chapter?

Another potential solution (yet definitely not optimal), could be to always re-download the last chapter downloaded which would solve the issue mentioned here:
> The obvious disadvantage is that if a file is downloaded incorrectly, I have to delete that file manually to trigger it to download again.

Thanks azy2k9
